// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxnqftyolfrpjziqcmxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4bnFmdHlvbGZycGp6aXFjbXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODEyMDEsImV4cCI6MjA2ODI1NzIwMX0.u5EZd3fbWVtvCqHasargC9SCZRMwjYPqgzIJeBR2a2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});